### ISSUE TITLE
希望能够隐藏“草稿详情”中的两行预留字

### ISSUE THREAD

**Issue by Sisyphean-a** [qxchuckle/vsc-drafts#1]
或者能否替换成一个按钮，点击之后实现相同的功能，然后在右下角消息弹窗中解释原因之类的
或者换一个名字（例如：提醒 或者 提醒.md这种），但是点击之后不是打开文件，而是打开消息弹窗同时回根目录
有些矫情，但是确实对强迫症来说，这两行文字有点不够美观，不知道好不好实现
最后，非常好的项目，解决了我的一些困扰，感谢！

**Comment by qxchuckle** [comment]
这两行字在下策，我正在考虑移除，但还没有找到合适的解决办法，能让用户能正确、符合常识、自然地在根目录创建文件。
这是vsocde api的一个问题，触发命令的viewItem总是最后一个选择的item，这就意味着，当点击视图空白处，不选中任何item，失去原来item焦点后，再点击标题栏的创建文件，会在最后一次打开的文件夹内创建，而不能正确在根目录创建。
监听选中切换可以正确获取没有选中的情况，这或许对我有用，但我仍在尝试。

**Comment by qxchuckle** [comment]
![image](https://github.com/qxchuckle/vsc-drafts/assets/55614189/4e8bb217-2616-4081-94f6-d8c7bea15f0f)

这样如何，api的问题没有直接到解决办法

**Comment by qxchuckle** [comment]
![image](https://github.com/qxchuckle/vsc-drafts/assets/55614189/cb9d7200-5b4a-4cae-97af-2ca7bef75a7d)

**Comment by qxchuckle** [comment]
![image](https://github.com/qxchuckle/vsc-drafts/assets/55614189/fcb255a0-f816-48a5-a097-6ac29ef1f601)

感觉加个描述更好

**Comment by Sisyphean-a** [comment]
> ![图像](https://private-user-images.githubusercontent.com/55614189/324311846-4e8bb217-2616-4081-94f6-d8c7bea15f0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTUwMzUsIm5iZiI6MTcxMzc1NDczNSwicGF0aCI6Ii81NTYxNDE4OS8zMjQzMTE4NDYtNGU4YmIyMTctMjYxNi00MDgxLTk0ZjYtZDhjN2JlYTE1ZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAyNTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NjY1YjEwOTA5Y2RlYzc5M2M1YTQ3YjY2MzNmOTI1MWYzNDZjYjYyOTcwN2Y5Yzk2MGJlZGUyZjlmOGNhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgAWEunCyIRQ4IRKnBdDeW-TX-ZjN2yK_5GCgzVSOg0)
> 
> 这样如何，api的问题没有直接解决方法

感谢！这个看起来舒服很多了

**Comment by qxchuckle** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/55614189/324311846-4e8bb217-2616-4081-94f6-d8c7bea15f0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTUwMzUsIm5iZiI6MTcxMzc1NDczNSwicGF0aCI6Ii81NTYxNDE4OS8zMjQzMTE4NDYtNGU4YmIyMTctMjYxNi00MDgxLTk0ZjYtZDhjN2JlYTE1ZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAyNTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NjY1YjEwOTA5Y2RlYzc5M2M1YTQ3YjY2MzNmOTI1MWYzNDZjYjYyOTcwN2Y5Yzk2MGJlZGUyZjlmOGNhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgAWEunCyIRQ4IRKnBdDeW-TX-ZjN2yK_5GCgzVSOg0)
> > 这样如何，api的问题没有直接解决方法
> 
> 谢谢！这个看起来舒服很多了

已推送0.1.4版本
