### ISSUE TITLE
ubuntu 系统 GitHub 远端草稿本更改文件内容失效

### ISSUE THREAD

**Issue by trouvailleme** [qxchuckle/vsc-drafts#5]
系统：  Operating System: Ubuntu 20.04.6 LTS
             Kernel: Linux 5.15.0-105-generic
             Architecture: x86-64
错误描述：
添加文件正常，但是修改文件有问题。如添加test.txt文件，填写内容保存后再点击该文件内容没有。

**Comment by qxchuckle** [comment]
我在ubuntu上未能复现这一问题，在保存时
![image](https://github.com/qxchuckle/vsc-drafts/assets/55614189/e007801c-12be-4222-a6fa-5b6eaab06803)
存在错误么

**Comment by trouvailleme** [comment]
> 我在ubuntu上未能复现这一问题，在保存时 ![image](https://private-user-images.githubusercontent.com/55614189/330040938-e007801c-12be-4222-a6fa-5b6eaab06803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDIwNTgsIm5iZiI6MTcxNTYwMTc1OCwicGF0aCI6Ii81NTYxNDE4OS8zMzAwNDA5MzgtZTAwNzgwMWMtMTJiZS00MjIyLWE2ZmEtNWI2ZWFhYjA2ODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEyMDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODBhYTJlODMzZDA3YWMzNmRjYTY4ZWI4YjgzNjUxNmU3ZWZlZjU1MDMyZGM0Y2FlNWI0YWJmZTM4Zjc5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJhbUhySK8IliuBObN-T4NBATch_5veTd35Yoq1ftQc) 存在错误么

成功了，可能是网络原因。还有一个问题就是我在win上面添加了个本地草稿，但是在ubuntu上有这个错误，能不能去掉这个通知，有点强迫症
![image](https://github.com/qxchuckle/vsc-drafts/assets/68146797/110b0957-ba73-4c15-990a-a00340d09312)

**Comment by qxchuckle** [comment]
不能跨系统访问本地草稿，所以通常在win和linux下都各自创建一个本地草稿，并保存在草稿列表中方便切换，这个提示我认为是有必要的，但在win上进行远端开发可能会经常需要切换，后续我会尝试增加路径和系统绑定的功能，自动切换，也会增加可以关闭不同类型提示的配置。

**Comment by trouvailleme** [comment]
> 不能跨系统访问本地草稿，所以通常在win和linux下都各自创建一个本地草稿，并保存在草稿列表中方便切换，这个提示我认为是有必要的，但在win上进行远端开发可能会经常需要切换，后续我会尝试增加路径和系统绑定的功能，自动切换，也会增加可以关闭不同类型提示的配置。

好的，非常感谢你的帮助与解答

**Comment by qxchuckle** [comment]
0.2.8版本已更新历史记录功能，会记录草稿本的访问历史，当当前配置的路径无法打开时，会自动在历史中选择当前系统最后一次打开的草稿本，避免在win进行远端工作后直接弹出找不到路径。
